---
settings:
  name: NetApp Cloud Tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación sobre niveles de nube de NetApp
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Empezar
    entries:
    - title: Obtenga más información sobre la organización en niveles de la nube de
        NetApp
      url: "/concept-cloud-tiering.html"
    - title: Transfiera los datos locales a la nube
      entries:
      - title: Nivel a Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Capas para almacenamiento de blobs de Azure
        url: "/task-tiering-onprem-azure.html"
      - title: Nivel de almacenamiento en Google Cloud
        url: "/task-tiering-onprem-gcp.html"
      - title: Nivel a StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Almacenamiento de objetos de nivel S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Configurar licencias
      url: "/task-licensing-cloud-tiering.html"
    - title: Preguntas frecuentes
      url: "/faq-cloud-tiering.html"
  - title: Utilice la organización por niveles en la nube de NetApp
    entries:
    - title: Administrar la clasificación de datos
      url: "/task-managing-tiering.html"
    - title: Administrar el almacenamiento de objetos
      url: "/task-managing-object-storage.html"
    - title: Probar el rendimiento de la nube
      url: "/task-tiering-test.html"
    - title: Ver descripción general de niveles para todos los clústeres
      url: "/task-tiering-onprem-overview.html"
    - title: Supervisar el estado de las alertas de niveles
      url: "/task-monitor-tiering-alerts.html"
  - title: Referencia
    entries:
    - title: Clases y regiones de almacenamiento compatibles con Amazon S3
      url: "/reference-aws-support.html"
    - title: Niveles y regiones de acceso de Azure compatibles
      url: "/reference-azure-support.html"
    - title: Clases y regiones de almacenamiento de Google Cloud compatibles
      url: "/reference-google-support.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir asistencia
      url: "/task-support-registration.html"
    - title: Obtener ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
